#!/usr/bin/bash

SPAWN_TERMINAL_COMMAND="xterm -title \"$1\" -e"

CONF_PATH="$HOME/.config/bash-console-runner/"
CONF_TERMINAL="terminal-emulator.conf"

COMMAND_TO_RUN="$1"

# options
DISABLE_NOHUP=false

function help_text {
	printf "\nMust feed one executable\n\n"
	printf "Use: bash-console-runner-start \e[32m<executable>\e[0m\n"
}

function error {
	printf "\e[31mERROR\e[0m: $1" >> /dev/stderr
	help_text
	return 1
}

function conf_detection {
	# $1 command_name
	if [ ! -d $CONF_PATH ]; then
		mkdir $CONF_PATH
	fi
	if [ ! -f "$CONF_PATH$CONF_TERMINAL" ]; then
		cp /etc/bash-console-runner/$CONF_TERMINAL $CONF_PATH
	fi

	while read CONF_LINE; do
		if [ ${CONF_LINE:0:1} != "#" ]; then
			break;
		fi
	done < "$CONF_PATH$CONF_TERMINAL"

	if [ -n "$CONF_LINE" ]; then
		SPAWN_TERMINAL_COMMAND=${CONF_LINE/"\$1"/$1}
	fi
}

function toggle_option {

	case $1 in

		"-disable-nohup")
			DISABLE_NOHUP=true
			;;
		*)
			return 1
			;;
	esac
}

ARG_COUNT=1
for ARG in "$@"; do
	if [ "${ARG:0:1}" = "-" ]; then
		toggle_option $ARG
		((ARG_COUNT++))
	else
		COMMAND_TO_RUN=$ARG
		break;
	fi
done


if [ $(($#-$ARG_COUNT)) -gt 0 ]; then
	if command -v $COMMAND_TO_RUN > /dev/null; then
		conf_detection $COMMAND_TO_RUN

		if [ "$DISABLE_NOHUP" = true ]; then
			$SPAWN_TERMINAL_COMMAND bash-console-runner ${@:ARG_COUNT}
		else
			nohup $SPAWN_TERMINAL_COMMAND bash-console-runner $* &>/dev/null &
		fi

	else
		error "command \e[31m$COMMAND_TO_RUN\e[0m does not exist\e[0m\n"
	fi
else
	error "too few arguments: you input \e[31m$#\e[0m arguments\n"
fi