#!/usr/bin/bash

function print_centered {
	# $1:first_block | $2:first_block_color | $3:second_block | $4:second_block_color
	[[ $# -eq 0 ]] && return 1

	declare -i TERM_COLS="$(tput cols)"
	declare -i str_len="${#1}+${#3}"
	[[ $str_len -ge $TERM_COLS ]] && {
		echo "$1";
		return 0;
	}

	declare -i filler_len="$(( (TERM_COLS - str_len) / 2 ))"
	spacer=" "
	filler=""
	for (( i = 0; i < filler_len; i++ )); do
		filler="${filler}${spacer}"
	done

	printf "%s$2 %s \e[0m$4 %s \e[0m%s" "$filler" "$1" "$3" "$filler"
	[[ $(( (TERM_COLS - str_len) % 2 )) -ne 0 ]] && printf "%s" "${ch}"
	printf "\n"

	return 0
}

print_centered $1 "\e[44m"
RUN=$*
TEMP_TIME_RECORD=`mktemp`
/usr/bin/time --format="%Es" -o "$TEMP_TIME_RECORD" $RUN
RETURN_NUMBER=$?
printf "\n"

ELAPSED_TIME=$(cat "$TEMP_TIME_RECORD" | grep -o '[0-9]\+:[0-9]\+.[0-9]\+')
if [[ $RETURN_NUMBER -eq 0 ]]; then
	print_centered "Process returned $RETURN_NUMBER" "\e[42m" "elapsed: $ELAPSED_TIMEs" "\e[30;43m"
else
	print_centered "Process returned $RETURN_NUMBER" "\e[41m" "elapsed: $ELAPSED_TIMEs" "\e[30;43m"
fi

printf "Press \e[30;47m ENTER ↲ \e[0m to continue: "
read
